# Generated by Django 5.2.1 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(null=True)),
                ('doctor_id', models.BigIntegerField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('rating_comments', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('app_rating', models.IntegerField(null=True)),
                ('added_by', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('customer_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('other_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('location', models.IntegerField(null=True)),
                ('profile_pic', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('refund_status', models.IntegerField(default=0)),
                ('refund_requested_date', models.DateField()),
                ('refund_processed_date', models.DateField(null=True)),
                ('appointment_id', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('refund_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('stripe_customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_customer_token_id', models.TextField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryTransactionData',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('currency', models.CharField(max_length=10, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('appointment_id', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('coupon_id', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('vendor_fee', models.IntegerField(null=True)),
            ],
        ),
    ]
