# Generated by Django 5.2.4 on 2025-08-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(null=True)),
                ('doctor_id', models.BigIntegerField(null=True)),
                ('user_id', models.BigIntegerField(null=True)),
                ('rating_comments', models.TextField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('app_rating', models.IntegerField(null=True)),
                ('added_by', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('other_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.TextField(null=True)),
                ('completed_first_analysis', models.BooleanField(default=False)),
                ('preferred_name', models.CharField(blank=True, max_length=110, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_unit', models.CharField(max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('height_unit', models.CharField(max_length=20, null=True)),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=50, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('country_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='administrator.countries')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to='customer.customerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_questions_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions_answers', to='customer.customerprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_questions_answers', to='customer.extra_questions')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.IntegerField(null=True)),
                ('refund_currency', models.CharField(max_length=10, null=True)),
                ('refund_status', models.CharField(max_length=255, null=True)),
                ('request_date', models.DateTimeField(null=True)),
                ('refund_date', models.DateTimeField(null=True)),
                ('refund_method', models.CharField(max_length=255, null=True)),
                ('refund_account_number', models.CharField(max_length=255, null=True)),
                ('refund_account_IFSC_code', models.CharField(max_length=255, null=True)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='analysis.appointmentheader')),
            ],
        ),
    ]
