# Generated by Django 5.2.4 on 2025-08-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
        ('customer', '0001_initial'),
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointments_got', models.IntegerField(null=True)),
                ('appointments_left', models.IntegerField(null=True)),
                ('package_price', models.IntegerField(null=True)),
                ('is_couple', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_package', to='customer.customerprofile')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='doctor.doctorprofiles')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='administrator.specializations')),
            ],
        ),
    ]
