# Generated by Django 5.2.4 on 2025-08-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_package'),
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggested_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_packages', to='customer.customerprofile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_packages', to='doctor.doctorpaymentrules')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_packages', to='doctor.doctorprofiles')),
            ],
        ),
    ]
