# Generated by Django 5.2.1 on 2025-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerprofile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer_profile_id',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
