# Generated by Django 5.2.4 on 2025-08-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_suggested_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_package',
            name='package_price',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='confirmation_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
