# Generated by Django 5.2.1 on 2025-05-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customerprofile_customer_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
