# Generated by Django 5.2.4 on 2025-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_package_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_package',
            name='expires_on',
            field=models.DateField(null=True),
        ),
    ]
