# Generated by Django 5.2.1 on 2025-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_user_id_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='completed_first_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
