# Generated by Django 5.2.4 on 2025-09-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_package_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
