# Generated by Django 5.2.1 on 2025-06-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_countries_representation'),
        ('customer', '0006_customerprofile_preferred_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='administrator.countries'),
        ),
    ]
