# Generated by Django 5.2.4 on 2025-09-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customerprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='guardian_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='guardian_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='guardian_relation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
