# Generated by Django 5.2.4 on 2025-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customerprofile_guardian_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='guardian_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
