# Generated by Django 5.2.1 on 2025-06-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_appointmentheader_confirmation_email_and_more'),
        ('customer', '0007_remove_customerprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarytransactiondata',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='temporarytransactiondata',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='analysis.appointmentheader'),
        ),
        migrations.AlterField(
            model_name='temporarytransactiondata',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='customer.customerprofile'),
        ),
    ]
