# Generated by Django 5.2.1 on 2025-06-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_temporarytransactiondata_appointment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarytransactiondata',
            old_name='user_id',
            new_name='customer',
        ),
    ]
