# Generated by Django 5.2.4 on 2025-09-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customerprofile_guardian_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='mob_country_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
