# Generated by Django 5.2.1 on 2025-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_user_id_temporarytransactiondata_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactiondata',
            name='gateway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temporarytransactiondata',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
