# Generated by Django 5.2.1 on 2025-07-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_appointmentheader_appointment_status'),
        ('customer', '0010_temporarytransactiondata_gateway_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryTransactionData',
            new_name='PreTransactionData',
        ),
    ]
