# Generated by Django 5.2.1 on 2025-07-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_temporarytransactiondata_pretransactiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreTransactionData',
        ),
    ]
