# Generated by Django 5.2.1 on 2025-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_extra_questions_customerprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_questions',
            name='group',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
