# Generated by Django 5.2.1 on 2025-07-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_extra_questions_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='height_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='weight_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
