# Generated by Django 5.2.4 on 2025-08-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_OTPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('exists', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('bill_for', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TextField(null=True)),
                ('appointment_for', models.CharField(max_length=20, null=True)),
                ('issue_date', models.DateField(auto_now=True)),
                ('issue_time', models.TimeField(auto_now=True, null=True)),
                ('service', models.CharField(max_length=60, null=True)),
                ('due_date', models.DateField()),
                ('vendor_fee', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('discounts', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField()),
                ('mode_of_pay', models.CharField(max_length=20, null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_OTPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('exists', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferredDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('doctor_ids', models.CharField(default='[]', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PreTransactionData',
            fields=[
                ('pretransaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('coupon_id', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('vendor_fee', models.IntegerField(null=True)),
                ('gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_link', models.CharField(max_length=300, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='analysis.appointmentheader')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='customer.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pretransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_transactions', to='general.pretransactiondata')),
            ],
        ),
        migrations.CreateModel(
            name='StripeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pretransaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_transactions', to='general.pretransactiondata')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('pretransaction_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='general.pretransactiondata')),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timezones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Timezone',
                'verbose_name_plural': 'User Timezones',
            },
        ),
    ]
