# Generated by Django 5.2.1 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_OTPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('exists', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_OTPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('exists', models.BooleanField(default=False)),
            ],
        ),
    ]
