# Generated by Django 5.2.1 on 2025-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_otps',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
