# Generated by Django 5.2.4 on 2025-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_reminder_sent_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferredDoctors',
        ),
        migrations.AlterField(
            model_name='phone_otps',
            name='phone',
            field=models.CharField(max_length=17),
        ),
        migrations.DeleteModel(
            name='UserTimeZone',
        ),
    ]
