# Generated by Django 5.2.1 on 2025-07-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_appointmentheader_appointment_status'),
        ('customer', '0012_delete_pretransactiondata'),
        ('general', '0002_userpreferreddoctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTransactionData',
            fields=[
                ('temp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('coupon_id', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('vendor_fee', models.IntegerField(null=True)),
                ('gateway', models.CharField(blank=True, max_length=20, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='analysis.appointmentheader')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_transaction_data', to='customer.customerprofile')),
            ],
        ),
    ]
