# Generated by Django 5.2.1 on 2025-07-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_pretransactiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretransactiondata',
            old_name='temp_id',
            new_name='pretransaction_id',
        ),
    ]
