# Generated by Django 5.2.4 on 2025-09-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_appointmentheader_status_detail'),
        ('general', '0003_delete_userpreferreddoctors_alter_phone_otps_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFileUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('common_file', models.FileField(null=True, upload_to='tests&common_files/')),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_files', to='analysis.appointmentheader')),
            ],
        ),
    ]
