# Generated by Django 5.2.4 on 2025-09-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customerprofile_mob_country_code'),
        ('general', '0004_commonfileuploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfileuploader',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_files', to='customer.customerprofile'),
        ),
    ]
