# Generated by Django 5.2.1 on 2025-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_rename_temp_id_pretransactiondata_pretransaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('bill_for', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TextField(null=True)),
                ('appointment_for', models.CharField(max_length=20, null=True)),
                ('issue_date', models.DateField(auto_now=True)),
                ('issue_time', models.TimeField(auto_now=True, null=True)),
                ('service', models.CharField(max_length=60, null=True)),
                ('due_date', models.DateField()),
                ('vendor_fee', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('discounts', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField()),
                ('mode_of_pay', models.CharField(max_length=20, null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField(null=True)),
            ],
        ),
    ]
