# Generated by Django 5.2.4 on 2025-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_commonfileuploader_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfileuploader',
            name='uploaded_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
