# Generated by Django 5.2.1 on 2025-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_otps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phone_otps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
