# Generated by Django 5.2.1 on 2025-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_email_otps_created_at_phone_otps_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretransactiondata',
            name='stripe_payment_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
