# Generated by Django 5.2.4 on 2025-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_reminder_sent_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_sent_history',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
