# Generated by Django 5.2.1 on 2025-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_pretransactiondata_stripe_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretransactiondata',
            name='stripe_payment_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
