# Generated by Django 5.2.4 on 2025-11-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_alter_reschedule_history_appointment'),
        ('general', '0008_alter_reminder_sent_history_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_admin_whatsapp_sent', models.BooleanField(default=False)),
                ('confirmation_customer_whatsapp_sent', models.BooleanField(default=False)),
                ('confirmation_doctor_whatsapp_sent', models.BooleanField(default=False)),
                ('confirmation_admin_email_sent', models.BooleanField(default=False)),
                ('confirmation_customer_email_sent', models.BooleanField(default=False)),
                ('confirmation_doctor_email_sent', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notifications', to='analysis.appointmentheader')),
            ],
        ),
    ]
