# Generated by Django 5.2.4 on 2025-11-03 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_alter_reschedule_history_appointment'),
        ('general', '0009_appointmentnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_sent_history',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_sent_history', to='analysis.appointmentheader'),
        ),
    ]
