# Generated by Django 5.2.4 on 2025-11-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_reminder_sent_history_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotifications',
            name='payment_reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='payment_reminder_47h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
