# Generated by Django 5.2.4 on 2025-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_appointmentnotifications_payment_reminder_24h_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotifications',
            name='appointment_reminders_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='on_time_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='one_day_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='one_hour_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='one_week_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentnotifications',
            name='three_days_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
