# Generated by Django 5.2.1 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponRedeemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('coupon_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=60, null=True)),
                ('discount_percentage', models.IntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InticureEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit', models.BigIntegerField(null=True)),
                ('net_expense', models.BigIntegerField(null=True)),
                ('net_income', models.BigIntegerField(null=True)),
                ('net_amount', models.BigIntegerField(null=True)),
                ('net_profit_usd', models.BigIntegerField(default=0)),
                ('net_expense_usd', models.BigIntegerField(default=0)),
                ('net_income_usd', models.BigIntegerField(default=0)),
                ('net_amount_usd', models.BigIntegerField(default=0)),
                ('currency', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesKnown',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('payout_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField(null=True)),
                ('payout_date', models.DateField(auto_now=True)),
                ('payout_time', models.TimeField(auto_now=True)),
                ('accepted_date', models.DateField(null=True)),
                ('accepted_time', models.TimeField(null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('base_amount', models.IntegerField(null=True)),
                ('inticure_fee', models.IntegerField(null=True)),
                ('payout_status', models.IntegerField(default=0)),
                ('payout_amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('location_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('report_remarks', models.TextField(null=True)),
                ('report_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationTimeDuration',
            fields=[
                ('specialization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('time_duration', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.BigIntegerField()),
                ('accepted_date', models.DateField(null=True)),
                ('accepted_time', models.TimeField(null=True)),
                ('total_earnings', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPayouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField(auto_now=True)),
                ('payout_time', models.TimeField(auto_now=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('total_payouts', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.IntegerField(null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('transaction_time', models.TimeField(auto_now=True)),
                ('payment_status', models.IntegerField(default=0)),
            ],
        ),
    ]
