# Generated by Django 5.2.4 on 2025-08-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('analysis', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententries',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='general.transactions'),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_payment_rules', to='administrator.specializations'),
        ),
        migrations.AlterUniqueTogether(
            name='generalpaymentrules',
            unique_together={('country', 'specialization', 'experience', 'doctor_flag', 'session_count')},
        ),
    ]
