# Generated by Django 5.2.1 on 2025-05-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagesknown',
            name='language_id',
        ),
        migrations.AddField(
            model_name='languagesknown',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
