# Generated by Django 5.2.1 on 2025-06-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_languagesknown_language_id_languagesknown_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='number_of_sessions',
            field=models.IntegerField(null=True),
        ),
    ]
