# Generated by Django 5.2.4 on 2025-10-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payouts',
        ),
        migrations.DeleteModel(
            name='TotalEarnings',
        ),
        migrations.DeleteModel(
            name='TotalPayouts',
        ),
    ]
