# Generated by Django 5.2.1 on 2025-06-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_plans_description_plans_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
