# Generated by Django 5.2.1 on 2025-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_location_countries_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='representation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
