# Generated by Django 5.2.1 on 2025-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_countries_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPaymentRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('country_name', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('doctor_flag', models.CharField(max_length=10, null=True)),
                ('yrs_of_experience', models.IntegerField(default=0, null=True)),
                ('general', models.BooleanField(default=True)),
            ],
        ),
    ]
