# Generated by Django 5.2.1 on 2025-06-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_doctorpaymentrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('doctor_flag', models.CharField(max_length=10, null=True)),
                ('yrs_of_experience', models.CharField(max_length=10, null=True)),
                ('general', models.BooleanField(default=True)),
                ('inticure_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
