# Generated by Django 5.2.1 on 2025-06-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_departments_ratedistribution'),
        ('doctor', '0013_alter_doctorprofiles_doctor_payment_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPaymentRates',
        ),
        migrations.AddField(
            model_name='ratedistribution',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_payment_rates', to='administrator.countries'),
        ),
        migrations.AddField(
            model_name='ratedistribution',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_payment_rates', to='administrator.departments'),
        ),
    ]
