# Generated by Django 5.2.1 on 2025-06-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_delete_doctorpaymentrates_ratedistribution_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='specialization',
        ),
    ]
