# Generated by Django 5.2.1 on 2025-06-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_remove_departments_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='price',
            new_name='reduction',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='ratedistribution',
            name='inticure_rate',
        ),
        migrations.AddField(
            model_name='plans',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='administrator.countries'),
        ),
        migrations.AddField(
            model_name='plans',
            name='max_reduction',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='plan_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ratedistribution',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CountryRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_rates', to='administrator.countries')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_rates', to='administrator.departments')),
            ],
        ),
    ]
