# Generated by Django 5.2.1 on 2025-06-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_rename_price_plans_reduction_remove_plans_id_and_more'),
        ('doctor', '0013_alter_doctorprofiles_doctor_payment_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateDistribution',
            new_name='DoctorRates',
        ),
    ]
