# Generated by Django 5.2.1 on 2025-06-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_rename_ratedistribution_doctorrates'),
        ('analysis', '0013_alter_appointmentheader_is_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntries',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('doctor_share', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='analysis.appointmentheader')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='administrator.transactions')),
            ],
        ),
    ]
