# Generated by Django 5.2.1 on 2025-06-18 09:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_paymententries'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententries',
            name='country_base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='doctor_base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='inticure_min_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='inticure_share',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='inticure_share_from_country_diff',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymententries',
            name='inticure_share_from_min_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
