# Generated by Django 5.2.1 on 2025-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_paymententries_country_base_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specialization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SpecializationTimeDuration',
        ),
    ]
