# Generated by Django 5.2.1 on 2025-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_specializations_delete_specializationtimeduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializations',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
