# Generated by Django 5.2.1 on 2025-06-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_specializations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializations',
            name='double_session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specializations',
            name='single_session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
