# Generated by Django 5.2.1 on 2025-06-30 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_specializations_double_session_duration_and_more'),
        ('doctor', '0031_remove_doctorprofiles_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryrates',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctorrates',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctorrates',
            name='country',
        ),
        migrations.AddField(
            model_name='countryrates',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_rates', to='administrator.specializations'),
        ),
        migrations.AddField(
            model_name='doctorrates',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_payment_rates', to='administrator.specializations'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
