# Generated by Django 5.2.1 on 2025-06-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_alter_doctorrates_doctor_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorrates',
            name='doctor_flag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrates',
            name='rate_per_session',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorrates',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_payment_rates', to='administrator.specializations'),
        ),
    ]
