# Generated by Django 5.2.1 on 2025-06-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_doctorrates_doctor_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryrates',
            name='session_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorrates',
            name='session_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
