# Generated by Django 5.2.1 on 2025-07-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_countryrates_session_type_doctorrates_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPaymentRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_payment_rules', to='administrator.countries')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_payment_rules', to='administrator.specializations')),
            ],
            options={
                'unique_together': {('country', 'specialization')},
            },
        ),
    ]
