# Generated by Django 5.2.1 on 2025-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_generalpaymentrules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpaymentrules',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='generalpaymentrules',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='couples',
            field=models.BooleanField(default=False),
        ),
    ]
