# Generated by Django 5.2.1 on 2025-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_remove_generalpaymentrules_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpaymentrules',
            name='doctor_flag',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='experience',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
