# Generated by Django 5.2.1 on 2025-07-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_generalpaymentrules_doctor_flag_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalpaymentrules',
            unique_together={('country', 'specialization', 'experience', 'doctor_flag')},
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='doctor_fee_couple',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='doctor_fee_single',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='user_total_fee_couple',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='user_total_fee_single',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalpaymentrules',
            name='doctor_flag',
            field=models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='generalpaymentrules',
            name='experience',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='generalpaymentrules',
            name='couples',
        ),
        migrations.RemoveField(
            model_name='generalpaymentrules',
            name='doctor_fee',
        ),
        migrations.RemoveField(
            model_name='generalpaymentrules',
            name='user_total_fee',
        ),
    ]
