# Generated by Django 5.2.1 on 2025-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_alter_generalpaymentrules_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='currency_symbol',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
