# Generated by Django 5.2.1 on 2025-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_countries_currency_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generalpaymentrules',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='pricing_name',
            field=models.CharField(blank=True, help_text="Name or label for this pricing rule (e.g. 'Basic 1-Session India', '3-Session Plan')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='session_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of sessions this rule applies to', null=True),
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='total_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='generalpaymentrules',
            unique_together={('country', 'specialization', 'experience', 'doctor_flag', 'session_count')},
        ),
    ]
