# Generated by Django 5.2.1 on 2025-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_alter_generalpaymentrules_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalpaymentrules',
            old_name='total_offer_price',
            new_name='actual_price_couple',
        ),
        migrations.AddField(
            model_name='generalpaymentrules',
            name='actual_price_single',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
