# Generated by Django 5.2.1 on 2025-07-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_rename_total_offer_price_generalpaymentrules_actual_price_couple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
