# Generated by Django 5.2.1 on 2025-07-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_alter_transactions_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrates',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='country',
        ),
        migrations.DeleteModel(
            name='CountryRates',
        ),
        migrations.DeleteModel(
            name='DoctorRates',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
