# Generated by Django 5.2.1 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentAnswers',
            fields=[
                ('appointment_answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_questions_id', models.IntegerField()),
                ('option_id', models.IntegerField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentHeader',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('appointment_status', models.IntegerField(default=0)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField(null=True)),
                ('appointment_time_slot_id', models.CharField(max_length=40, null=True)),
                ('escalated_date', models.DateField(null=True)),
                ('escalated_time_slot', models.CharField(max_length=20, null=True)),
                ('junior_doctor', models.IntegerField(null=True)),
                ('senior_doctor', models.IntegerField(null=True)),
                ('is_free', models.IntegerField(default=1)),
                ('followup_id', models.IntegerField(null=True)),
                ('booked_on', models.DateField(auto_now=True)),
                ('booked_on_time', models.TimeField(auto_now=True, null=True)),
                ('type_booking', models.CharField(max_length=20)),
                ('followup_remark', models.TextField(null=True)),
                ('followup_created_by', models.CharField(max_length=20, null=True)),
                ('followup_created_doctor_id', models.IntegerField(null=True)),
                ('language_pref', models.CharField(max_length=20, null=True)),
                ('gender_pref', models.CharField(max_length=20, null=True)),
                ('meeting_link', models.CharField(max_length=200, null=True)),
                ('senior_meeting_link', models.CharField(max_length=200, null=True)),
                ('customer_message', models.TextField(null=True)),
                ('payment_required', models.IntegerField(null=True)),
                ('payment_done', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentQuestions',
            fields=[
                ('appointment_questions_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOtpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('bill_for', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TextField(null=True)),
                ('appointment_for', models.CharField(max_length=20, null=True)),
                ('issue_date', models.DateField(auto_now=True)),
                ('issue_time', models.TimeField(auto_now=True, null=True)),
                ('service', models.CharField(max_length=60, null=True)),
                ('due_date', models.DateField()),
                ('vendor_fee', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('discounts', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField()),
                ('mode_of_pay', models.CharField(max_length=20, null=True)),
                ('doctor_id', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('category_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtpVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.BigIntegerField()),
                ('otp', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_type', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('customer_gender', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
