# Generated by Django 5.2.4 on 2025-08-23 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_couple', models.BooleanField(default=False)),
                ('is_junior', models.BooleanField(default=False)),
                ('alignment_minutes', models.IntegerField(blank=True, null=True)),
                ('session_status', models.CharField(default='started', max_length=20)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentHeader',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_couple', models.BooleanField(default=False)),
                ('appointment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('followup', models.BooleanField(default=False)),
                ('followup_remark', models.TextField(null=True)),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('type_booking', models.CharField(max_length=20, null=True)),
                ('language_pref', models.CharField(max_length=20, null=True)),
                ('gender_pref', models.CharField(max_length=20, null=True)),
                ('meeting_link', models.CharField(max_length=200, null=True)),
                ('senior_meeting_link', models.CharField(max_length=200, null=True)),
                ('customer_message', models.TextField(null=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('confirmation_method', models.CharField(max_length=20, null=True)),
                ('confirmation_phone_number', models.CharField(max_length=20, null=True)),
                ('confirmation_email', models.CharField(max_length=100, null=True)),
                ('file_is_open', models.BooleanField(default=True)),
                ('is_referred', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('booked_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentQuestionsAndAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('initiated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Suggested_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Up_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.CharField(max_length=200, null=True)),
                ('meeting_code', models.CharField(max_length=29, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('doctor_meeting_id', models.UUIDField(unique=True)),
                ('customer_1_meeting_id', models.UUIDField(unique=True)),
                ('customer_2_meeting_id', models.UUIDField(unique=True)),
                ('doctor_joined', models.BooleanField(default=False)),
                ('customer_1_joined', models.BooleanField(default=False)),
                ('customer_2_joined', models.BooleanField(default=False)),
                ('customer_1_attendence_confirmed', models.BooleanField(default=False)),
                ('customer_2_attendence_confirmed', models.BooleanField(default=False)),
                ('doctor_attendence_confirmed', models.BooleanField(default=False)),
                ('doctor_meeting_link', models.CharField(max_length=200, null=True)),
                ('customer_1_meeting_link', models.CharField(max_length=200, null=True)),
                ('customer_2_meeting_link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes_for_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed_Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('frequency', models.CharField(max_length=100, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed_Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_type', models.CharField(max_length=50)),
                ('customer_gender', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_date', models.DateTimeField(auto_now_add=True)),
                ('referral_notes', models.TextField(blank=True, null=True)),
                ('is_couple', models.BooleanField(default=False)),
                ('converted_to_appointment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Referral_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reschedule_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('initiated_on', models.DateTimeField(auto_now=True)),
                ('previous_start_time', models.DateTimeField(null=True)),
                ('previous_end_time', models.DateTimeField(null=True)),
                ('new_start_time', models.DateTimeField(null=True)),
                ('new_end_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
