# Generated by Django 5.2.4 on 2025-08-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0002_initial'),
        ('analysis', '0001_initial'),
        ('customer', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_session', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='administrator.specializations'),
        ),
        migrations.AddField(
            model_name='appointment_customers',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_customers', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='analysis_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysissession'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='followup_of_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_appointment', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='partner_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_appointment_header', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='administrator.specializations'),
        ),
        migrations.AddField(
            model_name='appointment_customers',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_customers', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions_and_answers', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='tempsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_questionnaire_answers', to='analysis.analysissession'),
        ),
        migrations.AddField(
            model_name='cancel_history',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_history', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='analysis.category'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.category'),
        ),
        migrations.AddField(
            model_name='doctor_suggested_plans',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_plans', to='doctor.doctorpaymentrules'),
        ),
        migrations.AddField(
            model_name='follow_up_notes',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_notes', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='follow_up_notes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_notes', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='meeting_tracker',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tracker', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='meeting_tracker',
            name='customer_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tracker_customer_1', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='meeting_tracker',
            name='customer_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tracker_customer_2', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='notes_for_patient',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_for_patient', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='notes_for_patient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_for_patient', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='notes_for_patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_for_patient', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='observation_notes',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_notes', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='observation_notes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_notes', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_answers', to='analysis.options'),
        ),
        migrations.AddField(
            model_name='prescribed_medications',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='prescribed_medications',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='prescribed_medications',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='prescribed_tests',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='prescribed_tests',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='prescribed_tests',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='analysis.category'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analysis.questionnaire'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions', to='analysis.questionnaire'),
        ),
        migrations.AddField(
            model_name='referral',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='referral',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='administrator.specializations'),
        ),
        migrations.AddField(
            model_name='doctor_suggested_plans',
            name='refferral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_plans', to='analysis.referral'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='analysis.referral'),
        ),
        migrations.AddField(
            model_name='referral_customer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_customers', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='referral_customer',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_customers', to='analysis.referral'),
        ),
        migrations.AddField(
            model_name='reschedule_history',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='analysis.appointmentheader'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment_customers',
            unique_together={('appointment', 'customer')},
        ),
        migrations.AddConstraint(
            model_name='meeting_tracker',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('doctor_meeting_id', models.F('customer_1_meeting_id')), _negated=True), models.Q(('doctor_meeting_id', models.F('customer_2_meeting_id')), _negated=True)), name='doctor_and_customer_id_different'),
        ),
        migrations.AlterUniqueTogether(
            name='referral_customer',
            unique_together={('referral', 'customer')},
        ),
    ]
