# Generated by Django 5.2.1 on 2025-05-28 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='category_id',
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analysis.questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='analysis.category'),
        ),
    ]
