# Generated by Django 5.2.4 on 2025-08-23 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_tracker',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tracker', to='analysis.appointmentheader'),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_1_attendence_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_1_joined',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_1_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_2_attendence_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_2_joined',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_2_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='doctor_attendence_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='doctor_joined',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='doctor_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='is_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
