# Generated by Django 5.2.1 on 2025-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_options_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentQuestionsAndAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AppointmentQuestions',
        ),
    ]
