# Generated by Django 5.2.1 on 2025-05-29 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_appointmentquestionsandanswers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentAnswers',
        ),
        migrations.RemoveField(
            model_name='appointmentquestionsandanswers',
            name='question_id',
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_answers', to='analysis.options'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions_and_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentquestionsandanswers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions', to='analysis.questionnaire'),
        ),
    ]
