# Generated by Django 5.2.4 on 2025-08-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_meeting_tracker_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_tests',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
