# Generated by Django 5.2.1 on 2025-05-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_delete_appointmentanswers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentquestionsandanswers',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions_and_answers', to='analysis.appointmentheader'),
        ),
    ]
