# Generated by Django 5.2.4 on 2025-08-26 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_prescribed_tests_submitted'),
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentheader',
            name='confirmation_email',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='confirmation_method',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='confirmation_phone_number',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='senior_meeting_link',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='type_booking',
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='doctor.doctorpaymentrules'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='package_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='payment_required',
            field=models.BooleanField(default=True),
        ),
    ]
