# Generated by Django 5.2.4 on 2025-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_appointmentheader_confirmation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_tracker',
            name='monitor_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meeting_tracker',
            name='reminder_task_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
