# Generated by Django 5.2.1 on 2025-06-02 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_rename_appointment_time_slot_id_appointmentheader_appointment_slot_and_more'),
        ('doctor', '0009_doctorpaymentrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='appointment_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='doctor.doctoravailableslots'),
        ),
    ]
