# Generated by Django 5.2.4 on 2025-08-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_meeting_tracker_monitor_task_id_and_more'),
        ('customer', '0005_customer_package_expires_on'),
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='package_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='doctor.doctorpaymentrules'),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='customer.customer_package'),
        ),
    ]
