# Generated by Django 5.2.1 on 2025-06-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentheader',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='type_booking',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
