# Generated by Django 5.2.4 on 2025-08-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
        ('analysis', '0007_appointmentheader_package_used_and_more'),
        ('customer', '0005_customer_package_expires_on'),
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentheader',
            name='followup_of_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_appointment', to='analysis.appointmentheader'),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_header', to='customer.customer_package'),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='payment_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_header', to='doctor.doctorpaymentrules'),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_header', to='administrator.specializations'),
        ),
    ]
