# Generated by Django 5.2.4 on 2025-09-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_appointmentheader_followup_of_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='confirmed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
