# Generated by Django 5.2.1 on 2025-06-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_appointmentheader_appointment_date_and_more'),
        ('customer', '0006_customerprofile_preferred_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentheader',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointmentquestionsandanswers',
            name='user',
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_questions_and_answers', to='customer.customerprofile'),
        ),
    ]
