# Generated by Django 5.2.1 on 2025-06-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_appointmentheader_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentquestionsandanswers',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
