# Generated by Django 5.2.4 on 2025-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_appointmentheader_confirmed_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentheader',
            name='status_detail',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
