# Generated by Django 5.2.4 on 2025-09-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_appointmentheader_status_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescrption_validity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_till', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescrption_validity', to='analysis.appointmentheader')),
            ],
        ),
    ]
