# Generated by Django 5.2.1 on 2025-06-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_rename_appointment_id_appointmentquestionsandanswers_appointment'),
        ('doctor', '0009_doctorpaymentrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentheader',
            name='junior_doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='senior_doctor',
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='doctor.doctorprofiles'),
        ),
    ]
