# Generated by Django 5.2.4 on 2025-09-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_prescrption_validity'),
        ('customer', '0009_customerprofile_mob_country_code'),
        ('doctor', '0012_delete_commonfileuploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescrption_validity',
            name='appointment',
        ),
        migrations.AddField(
            model_name='prescrption_validity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_validity', to='customer.customerprofile'),
        ),
        migrations.AddField(
            model_name='prescrption_validity',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_validity', to='doctor.doctorprofiles'),
        ),
        migrations.AddField(
            model_name='prescrption_validity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
