# Generated by Django 5.2.1 on 2025-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_remove_appointmentheader_junior_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='confirmation_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='confirmation_method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='confirmation_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
