# Generated by Django 5.2.1 on 2025-06-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_appointmentheader_confirmation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentheader',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='payment_required',
            field=models.BooleanField(default=False),
        ),
    ]
