# Generated by Django 5.2.4 on 2025-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_prescrption_validity_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_medications',
            name='validity',
            field=models.DateField(null=True),
        ),
    ]
