# Generated by Django 5.2.4 on 2025-09-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_prescribed_medications_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_1_meeting_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_2_meeting_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='doctor_meeting_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
