# Generated by Django 5.2.4 on 2025-09-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_meeting_tracker_customer_1_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_1_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='customer_2_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting_tracker',
            name='doctor_meeting_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
