# Generated by Django 5.2.1 on 2025-07-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentheader',
            name='appointment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
