# Generated by Django 5.2.1 on 2025-07-16 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_appointmentheader_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('specialization_id', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_couple', models.BooleanField(default=False)),
                ('is_junior', models.BooleanField(default=False)),
                ('alignment_minutes', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='analysis_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysissession'),
        ),
        migrations.AddField(
            model_name='appointmentquestionsandanswers',
            name='tempsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_questionnaire_answers', to='analysis.analysissession'),
        ),
    ]
