# Generated by Django 5.2.4 on 2025-11-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_meeting_tracker_customer_1_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedule_history',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='analysis.appointmentheader'),
        ),
    ]
