# Generated by Django 5.2.1 on 2025-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_analysissession_delete_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='is_couple',
            field=models.BooleanField(default=False),
        ),
    ]
