# Generated by Django 5.2.1 on 2025-07-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_appointmentheader_is_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='file_is_open',
            field=models.BooleanField(default=True),
        ),
    ]
