# Generated by Django 5.2.1 on 2025-07-18 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_appointmentheader_file_is_open'),
        ('customer', '0012_delete_pretransactiondata'),
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='appointment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_date', models.DateField(auto_now_add=True)),
                ('referral_notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='analysis.appointmentheader')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='customer.customerprofile')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='analysis.referral'),
        ),
    ]
