# Generated by Django 5.2.1 on 2025-07-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_alter_transactions_payment_status'),
        ('analysis', '0019_appointmentheader_appointment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='specialization_id',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='specialization_name',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='administrator.specializations'),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='administrator.specializations'),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_header', to='analysis.referral'),
        ),
    ]
