# Generated by Django 5.2.1 on 2025-07-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_remove_analysissession_specialization_id_and_more'),
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='appointment',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_by_dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_referrals', to='doctor.doctorprofiles'),
        ),
    ]
