# Generated by Django 5.2.1 on 2025-07-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_remove_referral_appointment_referral_referred_by_dr'),
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='session_status',
            field=models.CharField(default='started', max_length=20),
        ),
        migrations.CreateModel(
            name='Doctor_Suggested_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_plans', to='doctor.doctorpaymentrules')),
                ('refferral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_plans', to='analysis.referral')),
            ],
        ),
    ]
