# Generated by Django 5.2.1 on 2025-07-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_analysissession_session_status_and_more'),
        ('customer', '0012_delete_pretransactiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentquestionsandanswers',
            name='appointment',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_session', to='customer.customerprofile'),
        ),
    ]
