# Generated by Django 5.2.1 on 2025-07-22 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_remove_appointmentquestionsandanswers_appointment_and_more'),
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_by_dr',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='doctor.doctorprofiles'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='doctor.doctorprofiles'),
        ),
    ]
