# Generated by Django 5.2.1 on 2025-07-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_remove_referral_referred_by_dr_referral_referred_dr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOtpVerify',
        ),
        migrations.DeleteModel(
            name='OtpVerify',
        ),
    ]
