# Generated by Django 5.2.1 on 2025-07-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_delete_emailotpverify_delete_otpverify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referred_dr',
            new_name='referred_doctor',
        ),
    ]
