# Generated by Django 5.2.1 on 2025-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_rename_referred_dr_referral_referred_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='status_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
