# Generated by Django 5.2.1 on 2025-07-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_prescriptions'),
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentheader',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentheader',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentheader',
            name='appointment_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_header', to='doctor.doctoravailableslots'),
        ),
    ]
