# Generated by Django 5.2.1 on 2025-08-01 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_appointmentheader_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.appointmentheader')),
            ],
        ),
    ]
