# Generated by Django 5.2.1 on 2025-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_observation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation_notes',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
