# Generated by Django 5.2.1 on 2025-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_observation_notes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentheader',
            name='appointment_slot',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='escalated_date',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='escalated_time_slot',
        ),
        migrations.RemoveField(
            model_name='appointmentheader',
            name='is_free',
        ),
    ]
