# Generated by Django 5.2.1 on 2025-08-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_remove_appointmentheader_appointment_slot_and_more'),
        ('customer', '0015_customerprofile_height_unit_and_more'),
        ('doctor', '0049_remove_doctoravailableslots_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation_notes',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_notes', to='analysis.appointmentheader'),
        ),
        migrations.CreateModel(
            name='PrescribedMedications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('frequency', models.CharField(max_length=100, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=200)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='analysis.appointmentheader')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='customer.customerprofile')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=100)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='analysis.appointmentheader')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='customer.customerprofile')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tests', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.DeleteModel(
            name='Prescriptions',
        ),
    ]
