# Generated by Django 5.2.1 on 2025-08-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_alter_observation_notes_appointment_and_more'),
        ('customer', '0015_customerprofile_height_unit_and_more'),
        ('doctor', '0049_remove_doctoravailableslots_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescribedMedications',
            new_name='Prescribed_Medications',
        ),
        migrations.RenameModel(
            old_name='PrescribedTests',
            new_name='Prescribed_Tests',
        ),
        migrations.CreateModel(
            name='Follow_Up_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_notes', to='analysis.appointmentheader')),
            ],
        ),
    ]
