# Generated by Django 5.2.1 on 2025-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_rename_prescribedmedications_prescribed_medications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_medications',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescribed_tests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescribed_tests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
