# Generated by Django 5.2.1 on 2025-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_prescribed_medications_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribed_medications',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
