# Generated by Django 5.2.4 on 2025-08-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField()),
                ('doctor_id', models.BigIntegerField(null=True)),
                ('uploaded_time', models.TimeField(auto_now=True)),
                ('uploaded_date', models.DateField(auto_now=True)),
                ('analysis_info_text', models.TextField(null=True)),
                ('analysis_info_path', models.TextField(null=True)),
                ('file_name', models.TextField(null=True)),
                ('file_size', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentCancellationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField()),
                ('cancelled_date', models.DateField(auto_now=True)),
                ('cancelled_time', models.TimeField(auto_now=True)),
                ('cancelled_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('is_query', models.IntegerField(default=0)),
                ('is_reply', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFileUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.TimeField(auto_now=True, null=True)),
                ('uploaded_date', models.DateField(auto_now=True, null=True)),
                ('common_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_id', models.BigIntegerField()),
                ('prescription_id', models.BigIntegerField(null=True)),
                ('consumption_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(null=True)),
                ('mapped_doctor', models.IntegerField(null=True)),
                ('doctor_flag', models.CharField(max_length=10, null=True)),
                ('added_doctor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.BigIntegerField(null=True)),
                ('follow_up_for', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('medication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prescription_id', models.BigIntegerField()),
                ('medication', models.TextField()),
                ('duration_number', models.TextField()),
                ('duration', models.TextField()),
                ('side_effects', models.TextField()),
                ('consumption_detail', models.TextField()),
                ('can_substitute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfiles',
            fields=[
                ('doctor_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_flag', models.CharField(max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=12, null=True, unique=True)),
                ('email_id', models.CharField(max_length=50, null=True, unique=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('qualification', models.TextField(null=True)),
                ('certificate_no', models.TextField(null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('address', models.TextField(null=True)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='address_proofs/')),
                ('sign_file_name', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('doctor_bio', models.CharField(max_length=10000, null=True)),
                ('registration_year', models.CharField(max_length=10, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(max_length=500, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('experience', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administrator.countries')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.languagesknown')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='known_languages', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_available_hours', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='analysis.appointmentheader')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointment', to='administrator.specializations')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='doctor.doctorprofiles')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='administrator.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initiation_date', models.DateField(null=True)),
                ('completed_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='doctor.doctorprofiles')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPaymentRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_name', models.CharField(blank=True, help_text="Optional name for this doctor's specific pricing rule", max_length=100, null=True)),
                ('session_count', models.PositiveIntegerField(default=1, help_text='Number of sessions for this override')),
                ('custom_doctor_fee_single', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_user_total_fee_single', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_doctor_fee_couple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_user_total_fee_couple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price_single', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price_couple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.countries')),
                ('general_rule', models.ForeignKey(blank=True, help_text='Optional. Link to reusable rule template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to='administrator.generalpaymentrules')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.specializations')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_assignments', to='doctor.doctorprofiles')),
            ],
            options={
                'unique_together': {('doctor', 'specialization', 'country', 'session_count')},
            },
        ),
    ]
