# Generated by Django 5.2.4 on 2025-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payouts',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='payouts',
            name='initiation_date',
        ),
        migrations.AddField(
            model_name='payouts',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payouts',
            name='initiated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
