# Generated by Django 5.2.1 on 2025-05-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Calendar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctor.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailableSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availability', to='doctor.calendar')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availability', to='doctor.doctorprofiles')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availability', to='doctor.generaltimeslots')),
            ],
            options={
                'verbose_name_plural': 'Doctor Availability',
                'ordering': ['doctor', 'date', 'time_slot'],
            },
        ),
    ]
