# Generated by Django 5.2.1 on 2025-05-28 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_calendar_generaltimeslots_doctoravailableslots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='time_slot_from',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='time_slot_to',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='user_id',
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
