# Generated by Django 5.2.4 on 2025-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_payouts_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='is_prescription_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
