# Generated by Django 5.2.4 on 2025-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofiles_is_prescription_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='registration_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
