# Generated by Django 5.2.1 on 2025-05-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctorprofiles_time_slot_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='working_date_frm',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='working_date_to',
        ),
    ]
