# Generated by Django 5.2.1 on 2025-05-29 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctorprofiles_working_date_frm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlanguages',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofiles'),
        ),
    ]
