# Generated by Django 5.2.4 on 2025-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorprofiles_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='salutation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
