# Generated by Django 5.2.4 on 2025-09-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctorprofiles_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='doctor.doctorprofiles'),
        ),
    ]
