# Generated by Django 5.2.1 on 2025-05-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctorlanguages_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlanguages',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
