# Generated by Django 5.2.4 on 2025-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctorappointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='currency',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
