# Generated by Django 5.2.1 on 2025-05-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_rename_doctor_id_doctorlanguages_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlanguages',
            old_name='languages',
            new_name='language',
        ),
    ]
