# Generated by Django 5.2.4 on 2025-09-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_payouts_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='currency_symbol',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
