# Generated by Django 5.2.1 on 2025-05-29 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_languagesknown_language_id_languagesknown_id'),
        ('doctor', '0007_rename_languages_doctorlanguages_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlanguages',
            name='language',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.languagesknown'),
        ),
    ]
