# Generated by Django 5.2.1 on 2025-06-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_doctorlanguages_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPaymentRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('country_name', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('doctor_flag', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='doctor_payment_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorpaymentrates'),
        ),
    ]
