# Generated by Django 5.2.4 on 2025-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_payouts_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='mobile_country_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='whatsapp_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
