# Generated by Django 5.2.1 on 2025-06-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctorpaymentrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorlanguages',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='known_languages', to='doctor.doctorprofiles'),
        ),
    ]
