# Generated by Django 5.2.4 on 2025-09-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_appointmentheader_status_detail'),
        ('doctor', '0009_doctorprofiles_mobile_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonfileuploader',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_files', to='analysis.appointmentheader'),
        ),
        migrations.AddField(
            model_name='commonfileuploader',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
