# Generated by Django 5.2.4 on 2025-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_commonfileuploader_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonfileuploader',
            name='uploaded_date',
        ),
        migrations.RemoveField(
            model_name='commonfileuploader',
            name='uploaded_time',
        ),
        migrations.AddField(
            model_name='commonfileuploader',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonfileuploader',
            name='common_file',
            field=models.FileField(null=True, upload_to='tests&common_files/'),
        ),
    ]
