# Generated by Django 5.2.1 on 2025-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctorlanguages_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpaymentrates',
            name='general',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorpaymentrates',
            name='yrs_of_experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
