# Generated by Django 5.2.4 on 2025-09-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_commonfileuploader_uploaded_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonFileUploader',
        ),
    ]
