# Generated by Django 5.2.1 on 2025-06-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_doctorpaymentrates'),
        ('doctor', '0011_doctorpaymentrates_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='doctor_payment_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.doctorpaymentrates'),
        ),
        migrations.DeleteModel(
            name='DoctorPaymentRates',
        ),
    ]
