# Generated by Django 5.2.1 on 2025-06-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_departments_ratedistribution'),
        ('doctor', '0012_alter_doctorprofiles_doctor_payment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='doctor_payment_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.ratedistribution'),
        ),
    ]
