# Generated by Django 5.2.1 on 2025-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctorprofiles_doctor_payment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='department',
        ),
    ]
