# Generated by Django 5.2.1 on 2025-06-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_paymententries_country_base_rate_and_more'),
        ('doctor', '0014_remove_doctorprofiles_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.departments'),
        ),
    ]
