# Generated by Django 5.2.1 on 2025-06-24 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_specializations_delete_specializationtimeduration'),
        ('doctor', '0016_specializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='location',
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administrator.countries'),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='administrator.specializations'),
        ),
        migrations.DeleteModel(
            name='Specializations',
        ),
    ]
