# Generated by Django 5.2.1 on 2025-06-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_remove_doctorprofiles_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='addr_file_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='addr_file_size',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='profile_file_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='profile_file_size',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='reg_file_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='reg_file_size',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='sign_file_size',
        ),
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='signature',
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='address_proofs/'),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='registration_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='sign_file_name',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
