# Generated by Django 5.2.1 on 2025-06-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_specializations_delete_specializationtimeduration'),
        ('doctor', '0018_remove_doctorprofiles_addr_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctorspecializations',
            name='description',
        ),
        migrations.AddField(
            model_name='doctorspecializations',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='doctor.doctorprofiles'),
        ),
        migrations.AlterField(
            model_name='doctorspecializations',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='administrator.specializations'),
        ),
    ]
