# Generated by Django 5.2.1 on 2025-06-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_remove_doctorprofiles_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='email_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
