# Generated by Django 5.2.1 on 2025-06-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctorprofiles_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='email_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofiles',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
