# Generated by Django 5.2.1 on 2025-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_doctorprofiles_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
