# Generated by Django 5.2.1 on 2025-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_doctorprofiles_first_name_doctorprofiles_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
