# Generated by Django 5.2.1 on 2025-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_alter_doctorprofiles_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
