# Generated by Django 5.2.1 on 2025-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_alter_doctorprofiles_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
