# Generated by Django 5.2.1 on 2025-06-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_doctorprofiles_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofiles',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
