# Generated by Django 5.2.1 on 2025-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_doctorprofiles_accepted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='experience',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
