# Generated by Django 5.2.1 on 2025-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0027_doctorprofiles_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='rejection_reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
