# Generated by Django 5.2.1 on 2025-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctorprofiles_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiles',
            name='doctor_flag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
