# Generated by Django 5.2.1 on 2025-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_doctorprofiles_doctor_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofiles',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
