# Generated by Django 5.2.1 on 2025-06-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_doctorprofiles_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='department',
        ),
    ]
