# Generated by Django 5.2.1 on 2025-06-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_countryrates_session_type_doctorrates_session_type'),
        ('doctor', '0031_remove_doctorprofiles_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofiles',
            name='doctor_payment_rate',
        ),
        migrations.CreateModel(
            name='Doctor_DoctorRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_doctorrate', to='doctor.doctorprofiles')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_doctorrate', to='administrator.doctorrates')),
            ],
        ),
    ]
