# Generated by Django 5.2.1 on 2025-07-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_countryrates_session_type_doctorrates_session_type'),
        ('doctor', '0032_remove_doctorprofiles_doctor_payment_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailableslots',
            options={'ordering': ['doctor', 'date', 'time_slot']},
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofiles')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.specializations')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailableHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.calendar')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofiles')),
            ],
        ),
    ]
