# Generated by Django 5.2.1 on 2025-07-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_countryrates_session_type_doctorrates_session_type'),
        ('doctor', '0033_alter_doctoravailableslots_options_doctorappointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='doctor.calendar'),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointment', to='administrator.specializations'),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctoravailablehours',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_available_hours', to='doctor.calendar'),
        ),
        migrations.AlterField(
            model_name='doctoravailablehours',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_available_hours', to='doctor.doctorprofiles'),
        ),
    ]
