# Generated by Django 5.2.1 on 2025-07-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_generalpaymentrules'),
        ('doctor', '0034_doctorappointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPaymentAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_doctor_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_user_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.countries')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_assignments', to='doctor.doctorprofiles')),
                ('general_rule', models.ForeignKey(blank=True, help_text='Optional. Link to a reusable rule template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to='administrator.generalpaymentrules')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.specializations')),
            ],
            options={
                'unique_together': {('doctor', 'specialization', 'country')},
            },
        ),
    ]
