# Generated by Django 5.2.1 on 2025-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_doctorpaymentassignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpaymentassignments',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentassignments',
            name='custom_platform_fee',
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='couples',
            field=models.BooleanField(default=False),
        ),
    ]
