# Generated by Django 5.2.1 on 2025-07-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_alter_generalpaymentrules_unique_together_and_more'),
        ('doctor', '0036_remove_doctorpaymentassignments_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpaymentassignments',
            old_name='custom_doctor_fee',
            new_name='custom_doctor_fee_couple',
        ),
        migrations.RenameField(
            model_name='doctorpaymentassignments',
            old_name='custom_user_total_fee',
            new_name='custom_doctor_fee_single',
        ),
        migrations.RemoveField(
            model_name='doctorpaymentassignments',
            name='couples',
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='custom_user_total_fee_couple',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='custom_user_total_fee_single',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpaymentassignments',
            name='general_rule',
            field=models.ForeignKey(blank=True, help_text='Optional. Link to reusable rule template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to='administrator.generalpaymentrules'),
        ),
    ]
