# Generated by Django 5.2.1 on 2025-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_alter_generalpaymentrules_unique_together_and_more'),
        ('doctor', '0037_rename_custom_doctor_fee_doctorpaymentassignments_custom_doctor_fee_couple_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorpaymentassignments',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='custom_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='pricing_name',
            field=models.CharField(blank=True, help_text="Optional name for this doctor's specific pricing rule", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorpaymentassignments',
            name='session_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of sessions for this override'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpaymentassignments',
            unique_together={('doctor', 'specialization', 'country', 'session_count')},
        ),
    ]
