# Generated by Django 5.2.1 on 2025-07-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_rename_total_offer_price_generalpaymentrules_actual_price_couple_and_more'),
        ('doctor', '0039_rename_custom_offer_price_doctorpaymentassignments_actual_price_couple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpaymentassignments',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.countries'),
        ),
        migrations.AlterField(
            model_name='doctorpaymentassignments',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='administrator.specializations'),
        ),
        migrations.DeleteModel(
            name='Doctor_DoctorRate',
        ),
    ]
