# Generated by Django 5.2.1 on 2025-07-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_rename_total_offer_price_generalpaymentrules_actual_price_couple_and_more'),
        ('doctor', '0041_alter_doctorpaymentassignments_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorPaymentAssignments',
            new_name='DoctorPaymentRules',
        ),
    ]
