# Generated by Django 5.2.1 on 2025-07-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_category_description'),
        ('doctor', '0042_rename_doctorpaymentassignments_doctorpaymentrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to='analysis.appointmentheader'),
        ),
    ]
