# Generated by Django 5.2.1 on 2025-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_doctorappointment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='session_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
