# Generated by Django 5.2.1 on 2025-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_doctorappointment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
