# Generated by Django 5.2.1 on 2025-07-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctorappointment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='session_type',
        ),
    ]
