# Generated by Django 5.2.1 on 2025-07-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_remove_doctorappointment_session_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescriptions',
        ),
    ]
