# Generated by Django 5.2.1 on 2025-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_delete_prescriptions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentReshedule',
        ),
        migrations.DeleteModel(
            name='AppointmentTransferHistory',
        ),
        migrations.DeleteModel(
            name='DoctorAddedTimeSlots',
        ),
        migrations.DeleteModel(
            name='DoctorAvailableDates',
        ),
        migrations.DeleteModel(
            name='DoctorAvailableTimeslots',
        ),
        migrations.DeleteModel(
            name='DoctorCalenderUpdate',
        ),
        migrations.DeleteModel(
            name='JrDoctorEngagement',
        ),
        migrations.DeleteModel(
            name='JuniorDoctorSlots',
        ),
        migrations.DeleteModel(
            name='Obeservations',
        ),
        migrations.DeleteModel(
            name='PatientMedicalHistory',
        ),
        migrations.DeleteModel(
            name='RescheduleHistory',
        ),
        migrations.DeleteModel(
            name='SeniorDoctorAvailableTimeSLots',
        ),
        migrations.DeleteModel(
            name='SrDoctorEngagement',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.DeleteModel(
            name='Timeslots',
        ),
    ]
