# Generated by Django 5.2.1 on 2025-08-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_delete_appointmentreshedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailableslots',
            name='date',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslots',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctoravailableslots',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='generaltimeslots',
            name='date',
        ),
        migrations.DeleteModel(
            name='PrescriptionsDetail',
        ),
        migrations.DeleteModel(
            name='DoctorAvailableSlots',
        ),
        migrations.DeleteModel(
            name='GeneralTimeSlots',
        ),
    ]
